name = "codecomp"
version = "0.0.1"
license = "MIT"
maintainer = "limpid.mazarine@gmail.com"
author = "Han Tang"
copyright = "Copyright 2019-2026 Han Tang"
description = "Coarray Decomposition Library"
keywords = ["coarray", "Fortran"]

[features]
debug.flags = "-g"
debug.gfortran.flags = "-fcoarray=lib -lcaf_shmem"

release.flags = "-O3"
release.gfortran.flags = "-fcoarray=lib -lcaf_shmem"

[profiles]
debug = ["debug"]
release = ["release"]

[install]
library = true

[library]
source-dir = "src"

[[test]]
name = "test"
source-dir = "test"
main = "co_decomp_test.f90"
